version: "3"

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
      - ./postgres/create_table.sql:/docker-entrypoint-initdb.d/02_create_table.sql
      - ./postgres/insert_testdata.sql:/docker-entrypoint-initdb.d/03_insert_testdata.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root
